### ISSUE TITLE
puzzles prior to 10 may be incorrect and some are missing

### ISSUE THREAD

**Issue by bstreiff** [bstreiff/dungleon-keeper#1]
I started making screenshots after solving puzzle 10.

I was able to find a couple screenshots/photos of puzzles [3](https://mobile.twitter.com/__sleepingpanda/status/1491144982966968320), [4](https://twitter.com/BanditoJuan/status/1491466238958186498), [5](https://mobile.twitter.com/gamejamplus/status/1492173770659876875), and [8](https://twitter.com/Lipedal/status/1493071003878055938) and backfilled those from there, but it'd be nice to have independent verification.

**Comment by wintery-mix** [comment]
I found this log of solutions linked from the official Dungleon discord: https://public.amplenote.com/v9pKb8k54NRetqnjUodLsFKF

That discord also has all the answers in a thread under their #rules-discussion channel.
